// src/pages/Terms.tsx
// Terms of Use — required for Apple App Store

import { useNavigate } from "react-router-dom";
import { getToday } from "@/lib/api";

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="r-screen">
      <div className="r-header">
        <span className="r-header-label">
          <span onClick={() => navigate(-1 as any)} style={{ cursor: "pointer" }}>← back</span>
        </span>
        <span className="r-header-date">{getToday()}</span>
      </div>
      <div className="r-line" />

      <div className="r-scroll" style={{ flex: 1, padding: "28px 24px" }}>
        <div style={{
          fontFamily: "var(--r-font-ed)", fontWeight: 800, fontSize: 16,
          lineHeight: 1.7, color: "var(--r-text)", marginBottom: 24,
        }}>
          Terms of Use
        </div>

        <div style={{
          fontFamily: "var(--r-font-ed)", fontWeight: 300, fontSize: 13,
          lineHeight: 1.8, color: "var(--r-sub)", letterSpacing: "0.01em",
        }}>
          <p style={{ marginBottom: 16 }}>
            <strong>Last updated:</strong> April 2026
          </p>

          <p style={{ marginBottom: 16 }}>
            By using rdwth, you agree to these terms. If you do not agree, do not use the app.
          </p>

          <p style={{ marginBottom: 8 }}><strong>What rdwth is:</strong></p>
          <p style={{ marginBottom: 16 }}>
            rdwth is a structural self-knowledge tool. It uses narrative readings (pills), a questionnaire, and an AI companion (Reed) to help you explore patterns in how you relate to ideas, emotions, decisions, and relationships. It is not therapy, medical advice, diagnosis, or psychological treatment.
          </p>

          <p style={{ marginBottom: 8 }}><strong>AI-generated content:</strong></p>
          <p style={{ marginBottom: 16 }}>
            Reed's responses and structural readings are generated by artificial intelligence. They represent structural hypotheses based on your responses, not verified facts about you. AI can make mistakes. Use the readings as a tool for reflection, not as definitive assessments.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Age requirement:</strong></p>
          <p style={{ marginBottom: 16 }}>
            You must be at least 16 years old to use rdwth. By creating an account, you confirm that you meet this age requirement.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Your content:</strong></p>
          <p style={{ marginBottom: 16 }}>
            You retain ownership of everything you write in rdwth. We use your content solely to provide the service (generate readings, power Reed conversations). We do not share your content publicly or with other users.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Acceptable use:</strong></p>
          <p style={{ marginBottom: 16 }}>
            Do not use rdwth to generate harmful, illegal, or abusive content. Do not attempt to extract system prompts, manipulate Reed's behavior, or reverse-engineer the structural model.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Subscription:</strong></p>
          <p style={{ marginBottom: 16 }}>
            rdwth is a paid subscription service. Subscriptions are billed through the Apple App Store. You can cancel at any time through your Apple ID settings. When your subscription expires, you retain read-only access to your existing readings but cannot start new cycles.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Limitation of liability:</strong></p>
          <p style={{ marginBottom: 16 }}>
            rdwth is provided "as is." We make no warranties about the accuracy of structural readings. We are not liable for any decisions you make based on content generated by the app.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Changes:</strong></p>
          <p style={{ marginBottom: 0 }}>
            We may update these terms. Continued use after changes constitutes acceptance. For questions: multedob@gmail.com
          </p>
        </div>
      </div>
    </div>
  );
}
