// src/pages/Terms.tsx
// Termos de Uso — required for Apple App Store

import { useNavigate } from "react-router-dom";
import { getToday } from "@/lib/api";

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="r-screen">
      <div className="r-header">
        <span className="r-header-label">rdwth · termos</span>
        <span className="r-header-date">{getToday()}</span>
      </div>
      <div className="r-line" />

      <div className="r-scroll" style={{ flex: 1, padding: "28px 24px" }}>
        <div style={{
          fontFamily: "var(--r-font-ed)", fontWeight: 800, fontSize: 16,
          lineHeight: 1.7, color: "var(--r-text)", marginBottom: 24,
        }}>
          Termos de Uso
        </div>

        <div style={{
          fontFamily: "var(--r-font-ed)", fontWeight: 300, fontSize: 13,
          lineHeight: 1.8, color: "var(--r-sub)", letterSpacing: "0.01em",
        }}>
          <p style={{ marginBottom: 16 }}>
            <strong>Última atualização:</strong> abril de 2026
          </p>

          <p style={{ marginBottom: 16 }}>
            Ao usar o rdwth, você concorda com estes termos. Se não concordar, não use o app.
          </p>

          <p style={{ marginBottom: 8 }}><strong>O que é o rdwth:</strong></p>
          <p style={{ marginBottom: 16 }}>
            rdwth é uma ferramenta de autoconhecimento estrutural. Usa leituras narrativas (Pills), um questionário e uma companhia de IA (Reed) para ajudar você a explorar padrões em como se relaciona com ideias, emoções, decisões e vínculos. Não é terapia, aconselhamento médico, diagnóstico ou tratamento psicológico.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Conteúdo gerado por IA:</strong></p>
          <p style={{ marginBottom: 16 }}>
            As respostas de Reed e as leituras estruturais são geradas por inteligência artificial. Elas representam hipóteses estruturais baseadas nas suas respostas, não fatos verificados sobre você. IA pode errar. Use as leituras como ferramenta de reflexão, não como avaliações definitivas.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Age requirement:</strong></p>
          <p style={{ marginBottom: 16 }}>
            You must be at least 16 years old to use rdwth. By creating an account, you confirm that you meet this age requirement.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Your content:</strong></p>
          <p style={{ marginBottom: 16 }}>
            You retain ownership of everything you write in rdwth. We use your content solely to provide the service (generate readings, power Reed conversations). We do not share your content publicly or with other users.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Acceptable use:</strong></p>
          <p style={{ marginBottom: 16 }}>
            Do not use rdwth to generate harmful, illegal, or abusive content. Do not attempt to extract system prompts, manipulate Reed's behavior, or reverse-engineer the structural model.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Subscription:</strong></p>
          <p style={{ marginBottom: 16 }}>
            rdwth is a paid subscription service. Subscriptions are billed through the Apple App Store. You can cancel at any time through your Apple ID settings. When your subscription expires, you retain read-only access to your existing readings but cannot start new cycles.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Limitation of liability:</strong></p>
          <p style={{ marginBottom: 16 }}>
            rdwth is provided "as is." We make no warranties about the accuracy of structural readings. We are not liable for any decisions you make based on content generated by the app.
          </p>

          <p style={{ marginBottom: 8 }}><strong>Changes:</strong></p>
          <p style={{ marginBottom: 0 }}>
            We may update these terms. Continued use after changes constitutes acceptance. For questions: multedob@gmail.com
          </p>
        </div>
      </div>
    </div>
  );
}
