-- ============================================================
-- LUCID RAG CORPUS — Batch 1 (corpus v1.2)
-- Migration: 003_rag_corpus_batch1.sql
-- Structural Model Version: 3.0
-- Nodes: 16 (F1-N8 to F1-N10, F2-N8 to F2-N12, F3-N9 to F3-N15, F4-N9)
-- Total corpus after migration: 51 nodes
-- AFC applied: F5-N5 node_type corrected to "Tension"
-- ============================================================

INSERT INTO rag_corpus (id, node_id, family, node_type, density_class, macro_band, amplitude_min, amplitude_max, stage_min, stage_max, content_text, teleology_score, prescriptive_score, normative_score) VALUES

-- ============================================================
-- F1 — Base Existencial / Pré-Reflexiva
-- ============================================================

(gen_random_uuid(), 'F1-N8', 'F1', 'Declarative', 2, 'F1', 1.50, 2.30, 1.50, 2.30,
'Behave argues that no single explanatory level — neural firing, hormonal state, developmental history, genetic inheritance, cultural environment, or evolutionary selection — is sufficient to account for human behavior. Behavioral output is the product of interacting causal processes unfolding across nested and partially overlapping timescales. The book structures its analysis through an expanding temporal horizon: seconds before an act (neural activity), hours before (hormones), years before (developmental shaping), decades before (cultural conditioning), and millennia before (evolutionary pressures). These layers are not arranged as a linear hierarchy in which one level simply explains the next; rather, they form a dynamic stack in which each level both constrains and is conditioned by the others. Cognitive phenomena such as heuristics, bias, and rapid substitution processes occur within this architecture but do not originate independently of it. What appears at the psychological level as spontaneous judgment is treated as the surface expression of biological processes operating across multiple interacting strata. The framework situates cognition as an emergent layer within a multi-level causal system rather than as an autonomous domain.',
0, 0, 0),

(gen_random_uuid(), 'F1-N9', 'F1', 'Tension', 2, 'F1', 1.80, 2.40, 1.80, 2.40,
'The Wisdom of Insecurity identifies a structural self-reinforcing circuit within the divided field of experience: every effort the self-conscious ''I'' directs toward achieving security, certainty, or possession of its own experience intensifies the very division from which insecurity arises. The book describes this through what it calls the ''law of reversed effort'' — the observation that striving to grasp, stabilize, or improve experience operates through the same logic of subject-object separation that generates the original tension. The ''I'' is treated not as a biological subsystem or adaptive mechanism but as a reflexive construction produced by language, memory, and symbolic abstraction. It is a process of thought mistaking its own activity for an independent controller of experience. Because the attempt to control life presupposes this division, effort reinforces the structure it seeks to escape. The circuit cannot be exited through additional effort, since effort is the mechanism that sustains it. The book does not offer a causal explanation of how the division arose nor a technical method for eliminating it; instead, it frames insight into the structure of the division itself as the only shift available within the phenomenological framework it presents.',
0, 0, 0),

(gen_random_uuid(), 'F1-N10', 'F1', 'Tension', 2, 'F1', 1.60, 2.50, 1.60, 2.50,
'Man''s Search for Meaning presents extreme deprivation as a boundary condition for human psychology. In the concentration camps, external freedoms are progressively eliminated — property, status, autonomy, bodily security — until behavioral options narrow to minimal survival strategies. Within this limit context, individuals nonetheless diverge in observable stance and interpretation despite near-identical material constraints. The text identifies what it calls a residual freedom: not freedom from circumstance, but the capacity to adopt a stance toward unavoidable suffering. This freedom does not alter external conditions, suspend physiological stress, or guarantee survival; it operates strictly at the level of interpretation and response orientation. Meaning is not presented as abstract doctrine but as situational alignment with a perceived responsibility — toward a future task, a loved person, or an unfinished obligation. The framework does not deny structural determination; rather, it isolates a minimal domain of experiential orientation that appears to persist even when structural control approaches totality.',
0, 0, 0),

-- ============================================================
-- F2 — Estrutura Social / Identidade
-- ============================================================

(gen_random_uuid(), 'F2-N8', 'F2', 'Tension', 2, 'F2', 3.20, 4.40, 3.20, 4.40,
'Behave identifies a structural coupling embedded in the neurobiological substrates of social behavior: mechanisms that enhance in-group bonding simultaneously intensify out-group vigilance and hostility. Oxytocin, commonly associated with trust and affiliative bonding, is described as amplifying prosocial behavior within a defined group while heightening suspicion or defensive aggression toward those categorized as external. The Us/Them partition is fast, automatic, and supported by evolutionarily ancient circuitry; it precedes reflective justification and operates beneath explicit ideology. The tension exposed is not the accidental coexistence of altruism and aggression but their shared biological scaffolding. Cooperation and exclusion are not separate motivational systems but reciprocally reinforcing outputs of overlapping neural and hormonal architectures. Awareness of this coupling does not deactivate it. The book does not propose a biological escape from this structure; it frames the coexistence of solidarity and exclusion as an inherent feature of the evolved social brain.',
0, 0, 0),

(gen_random_uuid(), 'F2-N9', 'F2', 'Contrast', 2, 'F2', 3.00, 4.00, 3.00, 4.00,
'The Wisdom of Insecurity describes the ordinary sense of a separate ''I'' as a reflexive construction arising from language, memory, and symbolic abstraction rather than as an independently existing agent. Within this framework, the self that seeks security is generated by the very cognitive division that separates subject from object and then attempts to manage that separation. Effort to control life presupposes this division and therefore perpetuates it. The contrast developed in the book is not between competing metaphysical claims about the nature of the self, nor between alternative psychological architectures, but between two modes of experiencing: one structured around anticipatory grasping and narrative self-reference, and another in which experience unfolds without that reflexive overlay. The second mode is not described as a new mechanism or module but as the absence of compulsive self-division. The analysis remains phenomenological and linguistic; it does not appeal to evolutionary function or biological causation.',
0, 0, 0),

(gen_random_uuid(), 'F2-N10', 'F2', 'Tension', 2, 'F2', 3.40, 4.60, 3.40, 4.60,
'Why Buddhism Is True presents the mind as an evolutionary assemblage of semi-autonomous modules, each shaped to advance fitness under ancestral conditions. These modules are not treated as illusions or errors but as adaptive solutions to recurrent evolutionary problems. Within this framework, conscious deliberation does not originate behavior but interprets and narrates outputs generated by competing subpersonal systems. The narrative self functions primarily as a coherence-maintaining interface, retroactively organizing impulses into a unified story of agency that stabilizes social interaction and long-term planning. The tension identified is structural rather than metaphysical: the phenomenological sense of authorship is experientially real and functionally necessary, yet the causal architecture described distributes motivation across modular subsystems operating below awareness. Insight into this modular structure does not dissolve its operation or negate its adaptive role; recognition and mechanism remain distinct explanatory levels.',
0, 0, 0),

(gen_random_uuid(), 'F2-N11', 'F2', 'Declarative', 2, 'F2', 3.20, 4.20, 3.20, 4.20,
'Thinking, Fast and Slow presents human judgment as governed by two interacting processing modes described as System 1 and System 2 — explicitly characterized in the book as heuristic constructs rather than literal neurological subsystems. System 1 operates automatically and rapidly, generating coherent interpretations from limited evidence and producing impressions that are experienced as self-evident. Its outputs are shaped by associative memory, pattern completion, and affective tagging, with a bias toward internal coherence rather than evidential completeness. System 2 is slower and resource-intensive; it is capable of deliberate analysis and rule-based reasoning but is typically engaged only when System 1 signals difficulty or conflict. A central mechanism in this architecture is substitution: when confronted with a complex question, System 1 unconsciously answers a simpler related question without indicating that a replacement has occurred. The framework explains how judgments achieve subjective certainty under informational constraint while remaining agnostic about the biological substrates that enable these processes.',
0, 0, 0),

(gen_random_uuid(), 'F2-N12', 'F2', 'Declarative', 2, 'F2', 3.40, 4.40, 3.40, 4.40,
'Being Wrong describes a recurring escalation pattern in how individuals respond to belief challenges from others. The book identifies three default explanatory moves: attributing disagreement to the other person''s lack of information, then to insufficient reasoning capacity, and finally to deliberate distortion for corrupt purposes. This sequence is not framed as individual pathology but as a structural consequence of what the book calls the ''Cuz It''s True Constraint'' — the observation that beliefs are experienced as true rather than chosen. Because beliefs present themselves as accurate representations of reality, alternative beliefs are interpreted not as parallel constructions but as deviations requiring explanation. The escalation from ignorance to idiocy to malice describes how disagreement transitions from epistemic variance to categorical exclusion. The book treats this pattern as a recurrent feature of belief systems operating within communities, where identity and epistemology reinforce each other, rather than as evidence of isolated cognitive failure.',
0, 0, 0),

-- ============================================================
-- F3 — Integração Reflexiva
-- ============================================================

(gen_random_uuid(), 'F3-N9', 'F3', 'Declarative', 2, 'F3', 5.20, 6.20, 5.20, 6.20,
'Why Buddhism Is True proposes that the systematic mismatch between evolved emotional circuitry and modern environments constitutes the structural source of a specific form of suffering the book identifies with the Buddhist concept of dukkha. Within this framework, feelings are described as adaptive mechanisms calibrated for ancestral conditions that now misrepresent the actual value of their objects in modern contexts: the felt urgency of a craving, the apparent significance of a social slight, the sense of threat triggered by abstract information. The mismatch is not incidental but architectural — feelings evolved to motivate behavior toward fitness, not toward accurate valuation or wellbeing. The book characterizes the category of ''false feelings'' not as feelings that are unreal but as feelings whose implicit claims about the significance of their objects are systematically unreliable. This framework treats emotional experience as structurally decoupled from the assessment of its own accuracy, producing a condition in which the mechanism of response and the mechanism of evaluation operate from the same source.',
0, 0, 0),

(gen_random_uuid(), 'F3-N10', 'F3', 'Tension', 3, 'F3', 5.00, 6.00, 5.00, 6.00,
'Thinking, Fast and Slow introduces a second dual distinction — between the experiencing self and the remembering self — that exposes a structural conflict internal to the concept of wellbeing. The experiencing self registers utility moment by moment in real time, sensitive to duration and immediate affective tone. The remembering self constructs a retrospective narrative of events, disproportionately weighting peak intensity and ending while exhibiting relative insensitivity to duration. These two evaluative processes can generate systematically incompatible assessments of the same episode: an experience that produces more total suffering may be remembered more favorably if its conclusion is less painful. The tension identified is not between rationality and bias but between two functionally distinct systems of evaluation that operate under different informational logics. Optimizing one necessarily risks degrading the other. A life organized to maximize lived absorption or momentary affect may not align with the preferences articulated by the remembering self, which governs choice, narrative identity, and long-term decision. The framework leaves unresolved which evaluative system should serve as the reference point for policy or personal decision, rendering the conflict structural rather than correctable.',
0, 0, 0),

(gen_random_uuid(), 'F3-N11', 'F3', 'Tension', 2, 'F3', 5.40, 6.40, 5.40, 6.40,
'Being Wrong identifies a structural tension embedded in the cognitive architecture that makes human judgment possible. The same mechanisms that enable adaptive intelligence — inductive inference, pattern completion, rapid belief formation from incomplete evidence, and commitment to coherent interpretation — simultaneously generate systematic vulnerability to error. The book does not describe this as a defect to be eliminated but as an unavoidable feature of finite cognition operating under uncertainty. This produces an unresolved tension: the recommendation that individuals and institutions cultivate humility toward their own fallibility conflicts with the psychological mechanisms that stabilize belief once formed. Confirmation bias, the ''Cuz It''s True Constraint'', and the identity-forming function of belief collectively produce inertia against revision. The framework acknowledges that recognizing structural fallibility does not neutralize it. The tension between cognitive inevitability and aspirational epistemic openness remains structurally present rather than resolved.',
0, 0, 0),

(gen_random_uuid(), 'F3-N12', 'F3', 'Tension', 2, 'F3', 5.80, 6.50, 5.80, 6.50,
'Stealing Fire describes altered states of consciousness — grouped under the term ecstasis — as recurring neurobiological configurations associated with shifts in self-processing, temporal perception, motivation, and perceived informational density. These states are linked to mechanisms such as transient hypofrontality and alterations in the default mode network, and are reported to arise through diverse pathways including pharmacological intervention, extreme physical environments, contemplative practice, synchronized group ritual, and immersive technological design. The book advances the interpretive claim that the widespread pursuit of such states reflects a biologically rooted motivational tendency — labeled a ''fourth drive'' — though this characterization functions as a framing hypothesis rather than a settled evolutionary consensus. A structural tension runs throughout the argument: expanded access to ecstasis is presented as increasing cognitive flexibility, creativity, and social bonding, while the same mechanisms that attenuate self-boundaries and amplify cohesion also increase vulnerability to dependency formation, suggestibility, authority concentration, and risk escalation. The framework treats altered states not as inherently emancipatory or inherently destabilizing but as amplifiers operating within preexisting institutional, cultural, and economic configurations. The systemic consequences of broader access remain indeterminate: democratization may redistribute cognitive and experiential tools, yet it may equally intensify asymmetries of influence and control. The tension between enhancement and destabilization remains intrinsic rather than resolved.',
0, 0, 0),

(gen_random_uuid(), 'F3-N13', 'F3', 'Tension', 2, 'F3', 5.40, 6.40, 5.40, 6.40,
'Flow describes a recurrent experiential configuration in which attention becomes fully absorbed in a task whose perceived challenges match perceived skills above an individual threshold. Within this framework, subjective disorder — termed psychic entropy — arises when attention is fragmented by conflicting goals, whereas experiential coherence emerges when attention is structured around clear feedback and manageable challenge. The model positions control of consciousness, rather than external circumstance, as the primary determinant of lived quality. A structural tension appears in the empirical findings: activities that most frequently generate flow, such as work, are not consistently those individuals report preferring, revealing a divergence between momentary experiential quality and reflective evaluation. The framework implicitly assumes continuity between lived absorption and subsequent appraisal — that what is experienced as optimal in the moment will align with reflective judgment about what constitutes a good life. Yet the data suggest that these evaluative layers do not reliably converge. A second ambiguity concerns meaning: while repeated flow experiences are described as strengthening the organization of the self, the accumulation of such states does not automatically yield coherent long-term purpose. The model thus presents flow as a repeatable configuration of attention and skill under constraint, without resolving whether optimal moments integrate into stable life structure or remain episodic states whose retrospective valuation may diverge from their lived intensity.',
0, 0, 0),

(gen_random_uuid(), 'F3-N14', 'F3', 'Tension', 3, 'F3', 5.60, 6.50, 5.60, 6.50,
'Ego and Archetype presents psychological development as a recurrent oscillation between identification with a larger organizing center (ego-Self union) and differentiation from it (ego-Self separation). The Self, within this framework, functions as a conceptual representation of the total psyche — conscious and unconscious — while the ego represents the localized center of subjective awareness. The model describes repeated cycles of inflation, alienation, and renewed symbolic relation to unconscious contents, portraying individuation not as linear improvement but as increasing awareness of the ego''s limited scope within a wider psychic organization. A structural paradox lies at the center of the formulation: the Self is defined as inclusive of the ego, yet must be treated as analytically distinct in order to describe their interaction. This distinction is methodologically necessary while conceptually unstable. Symbols are treated as mediating forms that allow unconscious patterns to become experientially accessible without being reducible to literal propositions. The framework does not assert the ontological status of archetypal structures beyond their phenomenological and interpretive function; rather, it presents individuation as an ongoing dynamic of differentiation and integration whose endpoint, if any, remains undefined. The tension between analytic distinction and psychic totality remains intrinsic to the model.',
0, 0, 0),

(gen_random_uuid(), 'F3-N15', 'F3', 'Tension', 2, 'F3', 5.80, 6.50, 5.80, 6.50,
'The book advances a structural paradox: human beings are profoundly shaped by circumstance, yet do not appear to be exhaustively reducible to it. The camp environment demonstrates overwhelming systemic constraint over behavior, health, cognition, and survival probability. At the same time, the narrative documents variability in how individuals interpret and orient themselves toward those constraints. The framework asserts an irreducible domain of stance — an ability to relate to suffering in different ways — even when action options are nearly eliminated. Meaning emerges not from removing suffering but from positioning oneself in relation to it. This produces an unresolved asymmetry: structural conditions define the field of possible behaviors, while interpretive orientation seems comparatively less constrained. The model does not specify a biological or neurological mechanism that secures this interpretive latitude under extreme stress; instead, it treats it as a recurring empirical observation drawn from lived experience. Logotherapy generalizes this paradox beyond the camps, proposing that responsibility and self-transcendence describe recurrent motivational patterns rather than metaphysical properties. The tension between structural constraint and experiential orientation remains central and deliberately unclosed.',
0, 0, 0),

-- ============================================================
-- F4 — Integração Sistêmica Ampliada
-- ============================================================

(gen_random_uuid(), 'F4-N9', 'F4', 'Tension', 3, 'F4', 7.00, 8.00, 7.00, 8.00,
'The Fifth Discipline frames recurring organizational dysfunction as the product of structural dynamics rather than individual incompetence or malicious intent. Patterns of failure emerge from feedback loops, time delays, reinforcing and balancing processes, and system archetypes that generate behavior independent of the conscious goals of participants. Actors embedded within such systems experience outcomes as event-level problems while remaining structurally positioned inside circular causal processes they do not perceive. These feedback structures are treated as institutionally embedded and not eliminable through awareness alone — they persist across changes in personnel, strategy, and stated intention, constituting a structurally irreversible feature of complex organizational systems. At the same time, the book proposes that meaningful recalibration depends on the disciplined cultivation of new collective capacities — systems thinking, shared vision, reflective dialogue, and team learning. This produces a structural asymmetry: agents are described as constrained by systemic architecture, yet the proposed leverage point for change is located in shifts of perception, conversation, and aspiration among those same agents. The framework does not claim that systemic constraints disappear through awareness; instead, it treats organizational learning as an iterative process of partial recalibration within enduring structural boundaries. The tension between systemic determination and cultivated agency remains intrinsic rather than resolved.',
0, 0, 0);

-- ============================================================
-- Verification
-- ============================================================
-- Expected total after migration: 51 nodes
-- SELECT COUNT(*) FROM rag_corpus; → should return 51
-- SELECT family, COUNT(*) FROM rag_corpus GROUP BY family ORDER BY family;
-- Expected: F1=10, F2=12, F3=15, F4=9, F5=5