-- Seed: questionnaire content variations for IPE 1
-- Source: QUESTIONNAIRE_VARIATIONS_IPE1_v1.0.md
-- Total: 51 rows (17 blocks × 3 variations)
-- Note: fallback/subfallback are null; frontend falls back to questions.ts
-- Generated: 2026-04-14

INSERT INTO questionnaire_content_variations (block_id, ipe_level, variation_key, locale, content) VALUES

-- L1.1 — Directional Intention
('L1.1', 1.0, 'V1', 'en', '{"principal": "Think of a situation where you were doing something important — and something or someone pushed in another direction. What was organizing you in that moment? And what happened to that direction when the pressure came?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L1.1', 1.0, 'V2', 'en', '{"principal": "Describe a time when your original plan got interrupted — a genuine conflict between what you''d set out to do and what someone else needed or what circumstances demanded. Did you stay with your original intention, shift to the new thing, or split between the two? What made you decide?", "hint": "Focus on an actual moment when you had to choose between competing pulls.", "fallback": null, "subfallback": null}'::jsonb),
('L1.1', 1.0, 'V3', 'en', '{"principal": "Think of a time when you realized what you were doing wasn''t aligned with what actually matters to you — not because someone told you, but because you felt it. What were you doing, and what was the signal that told you something was off?", "hint": "This is a values-based anchor: internal misalignment, not external pressure.", "fallback": null, "subfallback": null}'::jsonb),

-- L1.2 — Sustained Discipline
('L1.2', 1.0, 'V1', 'en', '{"principal": "Think of a time when you were tired, unwilling, or couldn''t see the point — and there was something that needed to be done. Did you continue, stop, or do it halfway? And if you continued — what kept you going? If you stopped — what was missing?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L1.2', 1.0, 'V2', 'en', '{"principal": "Describe a situation where you were doing something that mattered to you — but over time, the struggle became real. The effort stayed hard, or the reward started to look less clear, or the cost got higher. What happened? Did you stay with it, find a different way, or eventually step back?", "hint": "This is about endurance over a longer arc — not an initial unwillingness, but fatigue setting in during the work.", "fallback": null, "subfallback": null}'::jsonb),
('L1.2', 1.0, 'V3', 'en', '{"principal": "Think of a time when you committed to something and then hit a point where continuing felt genuinely difficult — not just one bad day, but a sustained difficulty where you had to choose to keep going or let it go. What made you decide what to do?", "hint": "The focus is on the moment when continuing becomes a conscious choice, not automatic.", "fallback": null, "subfallback": null}'::jsonb),

-- L1.3 — Quality of Delivery
('L1.3', 1.0, 'V1', 'en', '{"principal": "Think of a time when you finished something and thought the result was good — and someone evaluated it differently. What happened to your criterion of ''good enough'' when that evaluation came?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L1.3', 1.0, 'V2', 'en', '{"principal": "Describe a situation where you completed work that met your own standards — and then the person receiving it pushed back, asked for changes, or indicated it wasn''t what they needed. How did you take that feedback? Did you defend your work, revise it, or something else?", "hint": "This captures the moment when what you judge as finished meets real resistance from the user/recipient.", "fallback": null, "subfallback": null}'::jsonb),
('L1.3', 1.0, 'V3', 'en', '{"principal": "Think of a time when you delivered something you believed in — and only later discovered it hadn''t accomplished what you''d intended, or it had created unintended consequences you hadn''t foreseen. What happened to your sense of what ''good work'' means when you saw the actual impact?", "hint": "The focus is on learning quality through full cycle — not judgment clash in the moment, but realization that follows real-world use.", "fallback": null, "subfallback": null}'::jsonb),

-- L1.4 — Continuous Improvement
('L1.4', 1.0, 'V1', 'en', '{"principal": "Think of an experience that could have changed the way you do things — at work, at home, in any area. Something that showed you something new or different. Did something actually change? If it did — what, and did the change stick? Or did things gradually go back to how they were?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L1.4', 1.0, 'V2', 'en', '{"principal": "Recall a moment when you learned a better way to do something — either from watching someone, from failing at your old way, or from trying something experimental. Did that learning shift how you actually operate now, or did you drift back to your habits?", "hint": "The focus is whether insight became actual behavior change.", "fallback": null, "subfallback": null}'::jsonb),
('L1.4', 1.0, 'V3', 'en', '{"principal": "Think of a time when feedback or experience revealed that your usual approach wasn''t working as well as you thought. Did you actually integrate that and adjust — or did it fade without changing much?", "hint": "This is about whether you genuinely evolve your practice, or just hear the lesson.", "fallback": null, "subfallback": null}'::jsonb),

-- L2.1 — Emotional Integration
('L2.1', 1.0, 'V1', 'en', '{"principal": "Think of a moment when you felt something intensely — anger, fear, frustration, shame, deep sadness — in a situation where you needed to keep functioning. Describe that moment briefly. Then: what did you do with what you were feeling? Did something organize your behavior in that moment, or did the emotion determine what happened?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L2.1', 1.0, 'V2', 'en', '{"principal": "Recall a situation where a strong emotion arrived while you had a job to do — you were afraid, furious, deeply hurt, or ashamed, but you still had to show up. What happened in that moment? Did the emotion take over what you did, or did something allow you to act despite it?", "hint": "The question is whether the feeling controlled your actions, or whether you had agency in the moment.", "fallback": null, "subfallback": null}'::jsonb),
('L2.1', 1.0, 'V3', 'en', '{"principal": "Think of a time when you felt something powerfully — and it mattered what you did next. Describe briefly: what was the emotion, what was at stake, and what did you actually do? Did you express it, contain it, let it drive your choices, or manage it somehow?", "hint": "This probes what happens when emotion and responsibility collide.", "fallback": null, "subfallback": null}'::jsonb),

-- L2.2 — Curiosity & Assimilation
('L2.2', 1.0, 'V1', 'en', '{"principal": "Think of a time when you became interested in something that had nothing to do with what you do day to day — something outside your area, your work, your usual domain. What happened when you went after it?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L2.2', 1.0, 'V2', 'en', '{"principal": "Describe a situation where someone you respect — or an experience — exposed you to an idea or skill that wasn''t part of your world. You hadn''t been looking for it, but when you encountered it, something caught. What did you do with that exposure? Did it change anything in how you work or think?", "hint": "This captures the relational angle: curiosity arriving through another person, not self-initiated.", "fallback": null, "subfallback": null}'::jsonb),
('L2.2', 1.0, 'V3', 'en', '{"principal": "Think of a time when you hit a problem or limitation in your regular work — and realized you didn''t have the knowledge or skill to solve it well. Did that gap pull you toward learning something new? Or did you work around it?", "hint": "The focus is on curiosity born from necessity or friction, not abstract interest.", "fallback": null, "subfallback": null}'::jsonb),

-- L2.3 — Energy Allocation
('L2.3', 1.0, 'V1', 'en', '{"principal": "Think of a phase of your life when several important things competed for your energy and attention at the same time — work, personal project, relationships, health, any combination. Not an atypical week, but a period when the demand was real and simultaneous. What ended up organizing where your energy went? How did you decide — or not decide — what got attention and what waited?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L2.3', 1.0, 'V2', 'en', '{"principal": "Recall a time when you had multiple significant commitments or responsibilities pulling at you simultaneously — no single crisis, but a real stretch where everything mattered. Describe how you navigated that. What principle or instinct guided where you focused? Or did you just react moment to moment?", "hint": "The question is whether you have a decision-making architecture for competing demands.", "fallback": null, "subfallback": null}'::jsonb),
('L2.3', 1.0, 'V3', 'en', '{"principal": "Think of a period when you were managing several important areas at once — relationships, work, something personal, maybe health or growth. How did you actually allocate your time and energy? Was there a logic to it, or did it feel more like chaos?", "hint": "This reveals whether you have clarity about what gets priority when everything can''t get everything.", "fallback": null, "subfallback": null}'::jsonb),

-- L2.4 — Self-Structure
('L2.4', 1.0, 'V1', 'en', '{"principal": "Think of the last time you discovered something about yourself that you didn''t know — or didn''t see. It could have come from another person, a situation, or a moment alone. What happened?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L2.4', 1.0, 'V2', 'en', '{"principal": "Describe a moment when you encountered a reflection of yourself — from another person''s honest observation, or from seeing yourself in an unexpected context — that revealed something you hadn''t recognized. What shifted in how you understand yourself?", "hint": "The discovery doesn''t have to be dramatic; it''s about gaining a clearer self-image.", "fallback": null, "subfallback": null}'::jsonb),
('L2.4', 1.0, 'V3', 'en', '{"principal": "Think of a moment when you caught yourself behaving in a way that surprised you — you did or said something and then thought, ''Where did that come from?'' What did that unexpected behavior teach you about who you''re becoming?", "hint": "This is self-discovered: you noticed something about yourself without external reflection.", "fallback": null, "subfallback": null}'::jsonb),

-- L3.1 — Structured Collaboration
('L3.1', 1.0, 'V1', 'en', '{"principal": "Think of a situation where you worked together with other people to do something — and had to find how to contribute in that process. What did you do together? And what, in that work, was specifically your contribution?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L3.1', 1.0, 'V2', 'en', '{"principal": "Recall a time when you were part of a team or group working toward a shared goal — not just alongside people, but interdependently. Describe what the group was creating or solving. Then: what was distinctly your role or part in it?", "hint": "This is about seeing yourself within a larger collaborative structure.", "fallback": null, "subfallback": null}'::jsonb),
('L3.1', 1.0, 'V3', 'en', '{"principal": "Think of the last time you were in a group working on something that required real coordination — where people depended on each other to deliver. What was specifically your part, and how did it connect to what others were doing?", "hint": "The question is how you position yourself and contribute within a collaborative constraint.", "fallback": null, "subfallback": null}'::jsonb),

-- L3.2 — Collective Navigation
('L3.2', 1.0, 'V1', 'en', '{"principal": "Think of a situation where the group around you operated in a way that wasn''t yours — a practice, an unspoken rule, or a way of doing things that you saw differently. What was that difference? And what did you do?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L3.2', 1.0, 'V2', 'en', '{"principal": "Describe a context where you observed the group or community operating according to norms, habits, or values that didn''t align with how you saw things. What was the difference in perspective? How did you respond — did you adapt, resist, speak up, observe quietly, or something else?", "hint": "The focus is on your agency when you encounter a group culture that isn''t yours.", "fallback": null, "subfallback": null}'::jsonb),
('L3.2', 1.0, 'V3', 'en', '{"principal": "Think of a time when you were in a group with an established way of doing something — a shared understanding or practice — that you experienced as off or misaligned with your own view. What did you do about that?", "hint": "This probes how you navigate being inside a system you see differently.", "fallback": null, "subfallback": null}'::jsonb),

-- L3.3 — Conflict Management
('L3.3', 1.0, 'V1', 'en', '{"principal": "Think of a situation where things got difficult between you and someone — a tension that didn''t resolve quickly. What happened? And how did things stay between you while it lasted?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L3.3', 1.0, 'V2', 'en', '{"principal": "Describe a conflict or sustained tension with someone in your life — something that lingered, wasn''t quick to resolve, and created awkwardness or distance. What happened while you were stuck in that conflict? How did you and that person relate to each other?", "hint": "Not a fight that got resolved in one conversation — a period of unresolved difficulty.", "fallback": null, "subfallback": null}'::jsonb),
('L3.3', 1.0, 'V3', 'en', '{"principal": "Think of a time when you were in a disagreement with someone important — and you noticed what was happening inside you during the conflict. Were you trying to win, trying to understand, trying to escape? What did you actually do with that awareness?", "hint": "The focus is on your internal experience during conflict, not the interpersonal dynamic.", "fallback": null, "subfallback": null}'::jsonb),

-- L3.4 — Relational Responsibility
('L3.4', 1.0, 'V1', 'en', '{"principal": "Think of a time when you realized — on your own or because someone showed you — that something you did affected a person in a significant way. What happened when that realization arrived?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L3.4', 1.0, 'V2', 'en', '{"principal": "Recall a moment when you became aware that an action of yours, or something you said, had impacted someone more deeply than you''d understood — maybe they told you, or you suddenly saw it. How did you take that in? What did you do?", "hint": "This is about the moment when you see your own agency from the other person''s side.", "fallback": null, "subfallback": null}'::jsonb),
('L3.4', 1.0, 'V3', 'en', '{"principal": "Think of something you did or said months ago — maybe even longer — that you later realized had a bigger effect on someone than you thought at the time. How did you come to understand that delayed impact? What did you do about it?", "hint": "The focus is on delayed recognition: realizing influence you didn''t see in the moment.", "fallback": null, "subfallback": null}'::jsonb),

-- L3.4_CP — Relational Responsibility (Alternate)
('L3.4_CP', 1.0, 'V1', 'en', '{"principal": "Think of a time when you realized — on your own or because someone showed you — that something you did affected a person in a significant way. What happened when that realization arrived?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L3.4_CP', 1.0, 'V2', 'en', '{"principal": "Describe a situation where someone showed you directly — through their words or their withdrawal — that your behavior had harmed or significantly affected them. How did you respond to that confrontation?", "hint": "This version emphasizes the relational feedback loop.", "fallback": null, "subfallback": null}'::jsonb),
('L3.4_CP', 1.0, 'V3', 'en', '{"principal": "Think of an instance where you gradually understood that your actions had ripple effects for another person. Did you address it? What made you act or stay silent?", "hint": "Some realizations come slow; this captures the slower version of accountability.", "fallback": null, "subfallback": null}'::jsonb),

-- L4.1 — Systemic Vision
('L4.1', 1.0, 'V1', 'en', '{"principal": "Think of a situation you experienced — at work, at home, in any context — where the outcome depended on how several things connected. It could be something that went wrong when you didn''t expect it, or something that worked in a way that surprised you. What did you notice about how those things influenced each other?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L4.1', 1.0, 'V2', 'en', '{"principal": "Tell me about a specific time when something went differently than expected — and when you looked closer, you realized it was because of multiple factors affecting each other, not just one cause. What were those factors, and how did they connect?", "hint": "This probes whether you can see systems — how parts affect the whole.", "fallback": null, "subfallback": null}'::jsonb),
('L4.1', 1.0, 'V3', 'en', '{"principal": "Think of a moment when you realized the outcome wasn''t about one thing going right or wrong — it was about how several things interacted. Describe that moment: what were the elements, and what did you see about their connections?", "hint": "The focus is on pattern recognition: can you hold multiple influences in view at once?", "fallback": null, "subfallback": null}'::jsonb),

-- L4.2 — Strategic Thinking
('L4.2', 1.0, 'V1', 'en', '{"principal": "Think of a decision you made thinking about what would happen after — big or small. Something where you looked ahead and tried to anticipate what that choice would produce over time. What did you take into account about what could happen further ahead?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L4.2', 1.0, 'V2', 'en', '{"principal": "Recall a time when you chose to do something differently than you normally would — because you were thinking about a longer-term consequence. You sacrificed something immediate to avoid or build something further out. What was that trade, and did it work out the way you anticipated?", "hint": "This captures the temporal angle: how you negotiate between immediate and delayed consequences in real time.", "fallback": null, "subfallback": null}'::jsonb),
('L4.2', 1.0, 'V3', 'en', '{"principal": "Think of a decision where you realized — either before or after — that your choice would affect not just you but someone else''s future. Were you aware of that influence at the time? How did it shape what you chose?", "hint": "The focus is simplified: did your choice account for impact on another person''s future?", "fallback": null, "subfallback": null}'::jsonb),

-- L4.3 — Knowledge as Presence
('L4.3', 1.0, 'V1', 'en', '{"principal": "Think of a situation where what you knew — an idea, a reading, an experience — was relevant, but the context around you wasn''t familiar with it. People didn''t expect to hear that from you, or the subject wasn''t obvious in that environment. What did you do with what you knew in that situation?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L4.3', 1.0, 'V2', 'en', '{"principal": "Recall a moment when you had knowledge or insight about something — from study, experience, or understanding — that seemed valuable in a situation, but the people around you didn''t recognize it as relevant or didn''t expect you to offer it. How did you navigate that? Did you speak it, hold it, or something in between?", "hint": "This is about the authority to speak what you know even when it''s unexpected.", "fallback": null, "subfallback": null}'::jsonb),
('L4.3', 1.0, 'V3', 'en', '{"principal": "Think of a time when you understood something important about a situation — something others in the room didn''t see or weren''t framing — and you had to decide whether to surface it. What made you decide what to do?", "hint": "The focus is on your agency around truth-telling in contexts where you''re not automatically believed.", "fallback": null, "subfallback": null}'::jsonb),

-- L4.4 — Integrating Presence
('L4.4', 1.0, 'V1', 'en', '{"principal": "Think of a situation where you were in a group — a meeting, a conversation, a project — and something changed in the dynamic from how you were present. Not necessarily from what you said, but from your presence itself. What happened? How did you notice that change?", "hint": null, "fallback": null, "subfallback": null}'::jsonb),
('L4.4', 1.0, 'V2', 'en', '{"principal": "Think of a specific time in a group — a meeting, a tense conversation, a collaborative moment — where something shifted in the room, and you suspect it had to do with how you were showing up, not what you said. What happened? How did you notice the shift?", "hint": "This is about presence as influence; not action, but being.", "fallback": null, "subfallback": null}'::jsonb),
('L4.4', 1.0, 'V3', 'en', '{"principal": "Recall a specific group interaction where you noticed that your own state — your energy, your listening, your emotional register — seemed to affect how others engaged. What was happening, and what changed?", "hint": "The focus is on sensing your own impact through group responsiveness.", "fallback": null, "subfallback": null}'::jsonb);
